"""
DOCX report generation.
Takes analysis results (per-doc extractions + cross-doc synthesis)
and produces a formatted .docx report.
"""

import io
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


def generate_report(documents_data: list[dict], synthesis: dict) -> bytes:
    """
    Generate a formatted .docx report from analysis results.

    Args:
        documents_data: list of per-document dicts, each with keys:
            - title: str
            - summary: str
            - themes: list of theme dicts (label, description, supporting_quote, confidence)
            - stance: str
            - flags: list of str
        synthesis: dict with keys:
            - recurring_themes: list
            - contradictions: list
            - overall_summary: str

    Returns:
        bytes — the .docx file content
    """
    doc = Document()

    # --- Title page ---
    title = doc.add_heading("Research Document Intelligence Report", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run("Generated by Research Doc Intelligence")
    run.italic = True
    run.font.size = Pt(11)
    run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    doc.add_paragraph()  # spacer

    # --- Overall summary ---
    if synthesis.get("overall_summary"):
        doc.add_heading("Executive Summary", level=1)
        doc.add_paragraph(synthesis["overall_summary"])

    # --- Per-document analysis ---
    doc.add_page_break()
    doc.add_heading("Per-Document Analysis", level=1)

    for doc_data in documents_data:
        doc.add_heading(doc_data["title"], level=2)

        # Summary
        if doc_data.get("summary"):
            p = doc.add_paragraph()
            p.add_run("Summary: ").bold = True
            p.add_run(doc_data["summary"])

        # Stance
        if doc_data.get("stance"):
            p = doc.add_paragraph()
            p.add_run("Stance / Sentiment: ").bold = True
            p.add_run(doc_data["stance"])

        # Themes
        themes = doc_data.get("themes", [])
        if themes:
            doc.add_heading("Extracted Themes", level=3)
            for i, theme in enumerate(themes, 1):
                p = doc.add_paragraph(style="List Number")
                p.add_run(theme.get("label", "Untitled")).bold = True

                if theme.get("description"):
                    doc.add_paragraph(theme["description"])

                if theme.get("supporting_quote"):
                    quote_p = doc.add_paragraph()
                    quote_p.paragraph_format.left_indent = Inches(0.5)
                    quote_run = quote_p.add_run(f'"{theme["supporting_quote"]}"')
                    quote_run.italic = True
                    quote_run.font.color.rgb = RGBColor(0x44, 0x44, 0x44)

                if theme.get("confidence"):
                    conf_p = doc.add_paragraph()
                    conf_p.paragraph_format.left_indent = Inches(0.5)
                    conf_run = conf_p.add_run(f"Confidence: {theme['confidence']}")
                    conf_run.font.size = Pt(10)
                    conf_run.font.color.rgb = RGBColor(0x88, 0x88, 0x88)
        else:
            doc.add_paragraph("No themes extracted from this document.")

        # Notable flags
        flags = doc_data.get("flags", [])
        if flags:
            doc.add_heading("Notable Flags", level=3)
            for flag in flags:
                p = doc.add_paragraph(flag, style="List Bullet")

        doc.add_paragraph()  # spacer between docs

    # --- Cross-document synthesis ---
    doc.add_page_break()
    doc.add_heading("Cross-Document Synthesis", level=1)

    # Recurring themes
    recurring = synthesis.get("recurring_themes", [])
    if recurring:
        doc.add_heading("Recurring Themes", level=2)
        for theme in recurring:
            p = doc.add_paragraph(style="List Number")
            p.add_run(theme.get("label", "Untitled")).bold = True

            if theme.get("appears_in"):
                src_p = doc.add_paragraph()
                src_p.paragraph_format.left_indent = Inches(0.25)
                src_run = src_p.add_run(f"Appears in: {', '.join(theme['appears_in'])}")
                src_run.font.size = Pt(10)
                src_run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

            if theme.get("synthesis"):
                doc.add_paragraph(theme["synthesis"])
    else:
        doc.add_paragraph("No recurring themes identified across documents.")

    # Contradictions
    contradictions = synthesis.get("contradictions", [])
    if contradictions:
        doc.add_heading("Contradictions & Tensions", level=2)
        for contra in contradictions:
            p = doc.add_paragraph(style="List Number")
            p.add_run(contra.get("description", "No description"))

            if contra.get("sources"):
                src_p = doc.add_paragraph()
                src_p.paragraph_format.left_indent = Inches(0.25)
                src_run = src_p.add_run(f"Sources: {', '.join(contra['sources'])}")
                src_run.font.size = Pt(10)
                src_run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)
    else:
        doc.add_paragraph("No contradictions identified across documents.")

    # --- Export to bytes ---
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.read()